openapi: 3.0.0
info:
  version: 1.0.0
  title: Bluetooth API from Bus database
  description: The Bluetooth table from the Bus database

servers:
  - url: http://localhost:5500

paths:
  /bluetooth/devices:
    get:
      description: Get all the devices in the data base
      responses:
        "200":
          description: Users are returned
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Devices"
              

  /bluetooth/{mac}:
    get:
      description: Get the connection history of an user by his mac address
      parameters:
        - name: mac
          in: path
          required: true
          description: Mac address of the device to get
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: History is returned
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
                
  /bluetooth/{from}/{to}:
    get:
      description: Get all devices connected in the interval of time
      parameters:
        - name: from
          in: path
          required: true
          description: min time
          schema:
            type: integer
            format: int64
        - name: to
          in: path
          required: true
          description: max time
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Return devices connected in this interval
          

  /bluetooth/device/add:
    post:
      description: Add a device to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddDevices"
      responses:
        "200":
          description: The user is added
  
  /qrcode/connections:
    get:
      description: Get All the connections
      responses:
        "200":
          description: Connections are returned
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Devices"
              
  

components:
  schemas:
    AddDevices:
      type: object
      required:
        - login
      properties:
        address:
          type: string
        name:
          type: string
        time:
          type: number
        
    Device:
      type: object
      properties:
        address:
          type: string
        name:
          type: string
        time:
          type: number
          
    Devices:
      type: array
      items: 
        $ref: "#/components/schemas/Device"


