version: "3"

services:
  db:
    image: "mariadb"
    container_name: "bus_db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bluetooth"
    volumes:
      - "bus_data:/var/lib/mysql"

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: "phpmyadmin"
    ports:
      - "8080:80"
    volumes:
      - "/sessions"

volumes:
  bus_data: ~
